# amd: added these two
env:
  - CODE_TESTS_WORKSPACE=$TRAVIS_BUILD_DIR/src/test/fixtures

#
# boilerplate https://code.visualstudio.com/api/working-with-extensions/continuous-integration
#

language: node_js
os:
  - osx
  - linux
node_js: 8

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

script:
  - |
    echo ">>> Compile vscode-test"
    yarn && yarn compile
    echo ">>> Compiled vscode-test"
    cd sample
    echo ">>> Run sample integration test"
    yarn && yarn compile && yarn test

cache: yarn
